---
title: "Analyzing Trends in Crime Against Persons: Insights from the Toronto Police Annual Statistical Report"
author: "Mohammed Yusuf Shaikh"
thanks: "Code and data are available at: LINK."
date: today
date-format: long
abstract: "Public Safety and security are a paramount concern in the 20th century, the analysis of statistics in Victimology helps to visualize and derive the conclusions of urban crime dynamics. This analytical report delves into the trends of victims of a certain crime in Toronto from the year 2014 to 2022. Through a series of data visualization approach to examine the relationship between crime incidents and demographic factors. The data reveals significant fluctuations in crime rates in correspond to the socio-economic shifts, including a notable dip in crimes reported during pandemic between 2019-2020. The visualization of the certain trends provides a compelling narrative on the dynamics of victims of crime in Toronto, advocating for all the policymakers to call for a reevaluation of current approaches to public safety and crime prevention."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(AER)
library(opendatatoronto)
library(dplyr)
library(readr)
library(janitor)
library(ggplot2)

# Loading Clean data & Read data
cleaned_victim_data <- read_csv(cleaned_data, file="outputs/data/cleaned_lead_data.csv")
```


# Introduction
The concern of Public safety in the Urban society is a necessary step towards safeguarding people of that community. The city of Toronto has various socio-economic challenges one of them being Crime against a person. A crime incident might leave a victim and our report aims to explore the patterns and trend of crimes against the person. The paper aims to understand how this trends have evolved among victims and analyzing there  demograpics from 2014 to 2022. To elaborate, the report context is not only quantifying crime victims but also interpret and explain whereby it motivates to a better approach towards urban safety and policies. The Criminal victimization is a frightening and unsettling experience for many Canadians (Cite). 

Victimology is a vast sub-category of criminology to understand various emotional factors and its causation, however based on our police annual report – victims of  crime showcase a statistical record based on which the report will share the knowledge to work on the gap to understand between victim demographics and crime. This report addresses this gap by visualizing crime statistics through a demographic lens, thereby unveiling patterns that may not be evident in numerical data alone

Through R programming language [@R] we analyze the data obtained from Open data Toronto [Open data Toronto]. This dataset provides a detailed account of all recorded count of victim under the jurisdiction of the Toronto Police Services over an eight-period. Our research offers an examination of cleaned data points and produced visual formats that reveal the shapes the crime type as well as their victims across different genders and age cohorts. The analysis, supplemented with various analytical tools like Tidyverse [@tidyverse], Janitor [@janitor], and Knitr [@knitr], delves deep into the trends, revealing patterns that could have implications for policy formulation and implementation.

The Introduction is followed by the Data section. Within the data section we talk about the data source used for this report, the data cleaning process applied and the result that is the visual analysis of trends and pattern involved. The Discussion section shares additional insights into the data findings, as well as discussing measurement errors and limitations of this analysis. Lastly, the document summarizes the analysis.

# Data











# References

